project:
  type: website
  output-dir: docs
  execute-dir: project

resources:
  - "img/"

website:
  site-url: "https://nascent-peru.github.io/"
  repo-url: "https://github.com/NASCENT-Peru/NASCENT-Peru.github.io"
  title: "NASCENT-PERU"
  description: "NAture-positive SCenarios for ENvironmental Transitions: Peru"
  #image: img/NASCENT_logo_vertical.jpg
  #favicon: img/NASCENT_logo_no_text.jpg.png

  navbar:
    background: "white"
    foreground: "dark"
    pinned: true
    logo: img/NASCENT_logo_no_text.jpg.png
    left:
      - project/project.qmd
      - menu:
              - project/project_scrolly.qmd
              - scenarios/scenarios.qmd
        text: "Outputs"
      - impressions/impressions.qmd
      - glossary/glossary.qmd
      - menu:
              - about/team.qmd
              - about/funding.qmd
              - about/contributers.qmd
        text: "Info"
    right:
      - icon: github
        href: https://github.com/blenback/NASCENT-Peru
      - icon: linkedin
        href: https://www.linkedin.com/company/nascent-peru
      - icon: facebook
        href: https://www.facebook.com/profile.php?id=61557948733975
      - text: "{{< iconify simple-icons zenodo size = Large >}}"
        href: https://zenodo.org/communities/nascent-peru
      - icon: mortarboard
        href: https://plus.ethz.ch/research/forschungsprojekte/NASCENT-PERU.html/
      - icon: envelope
        aria-label: email
        href: "mailto:bblack@ethz.ch"


preview:
  port: 22222
  browser: true
  watch-inputs: false
  navigate: true


format:
  html:
    css: "styles.css"
    fontsize: 1.1em
    theme:
      - cosmo
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    page-layout: article
    grid:
      sidebar-width: 400px
      body-width: 1100px
      margin-width: 150px
      gutter-width: 1.5rem
popover-glossary:
  path: glossary.yml
csl: vancouver.csl

babelquarto:
  languagecodes:
  - name: es
    text: "Español"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['es']
title-es: NASCENT-PERU
lang: en
#
# execute:
#   freeze: false
