project:
  type: website
  output-dir: docs

website:
  site-url: "https://nascent-peru.github.io/"
  repo-url: "https://github.com/NASCENT-Peru/NASCENT-Peru.github.io/"
  title: "NASCENT-PERU"
  description: "NAture-positive SCenarios for ENvironmental Transitions: Peru"
  #image: img/NASCENT_logo_vertical.jpg
  #favicon: img/NASCENT_logo_no_text.jpg.png

  navbar:
    background: "white"
    foreground: "dark"
    pinned: true
    logo: img/NASCENT_logo_no_text.jpg.png

     # your sub-pages
    left:
      - project.qmd
      - impressions.qmd
      - glossary.qmd
      - menu:
              - team.qmd
              - funding.qmd
        text: "Info"


    # your social media handles
    right:
      - icon: github
        href: https://github.com/blenback/NASCENT-Peru
      - icon: mortarboard
        href: https://plus.ethz.ch/research/forschungsprojekte/NASCENT-PERU.html/
      - icon: envelope
        aria-label: email
        href: "mailto:bblack@ethz.ch"


preview:
  port: 22222
  browser: true
  watch-inputs: true
  navigate: true


format:
  html:
    fontsize: 1.1em
    theme:
      - cosmo
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true

babelquarto:
  languagecodes:
  - name: es
    text: "Español"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['es']
title-es: NASCENT-PERU
lang: en


