on:
  workflow_dispatch:
  push:
    branches: main

name: Render multi-lingual website and publish to gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install R
        uses: r-lib/actions/setup-r@v2 
      - name: Set up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2 
        with:
          packages: |
            any::data.table
            any::fontawesome
            any::pagedown
            any::readxl
            any::bib2df
            any::rmarkdown
            any::leaflet
            any::tidyverse
            any::mapview
            github::quarto-dev/quarto-r
            github::ropensci-review-tools/babelquarto
      - name: Render website with Babelquarto
        run: Rscript -e 'babelquarto::render_website()'
      - name: Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
